server {
	server_name localhost
	listen 8000
	root /www
	error_page 404 /html/404.html
	error_page 403 /html/403.html

	location / {
		allow_methods GET
	}
}

/// per request potentially

-- if directory listing thing: check "dir yes" and put the contents of the directory into a string
send back to debora:

- type (dir, error, CGI, path)
- std::string full path
- status code
- isCGI boolean

--> 


first time 404 i find it, get specific one for that server. if i 