server {
	listen 80
	server_name momoserv

	location / {
		allow_methods GET
		index index.html
		root /Users/naomisterk/codam/webbieservie/www/html
	}

	location .py {
		root /cgi-bin
		allow_methods POST
		upload_dir /Users/naomisterk/codam/webbieservie/www/uploads
	}
}