server {
	listen localhost:80
	listen 80
	listen 127.000.001:8080
	listen 127.000.001
	server_name momoserv
	root /Users/naomisterk/codam/webbieservie/www/html
	allow_methods GET
	index index.html

	location .py {
		root /cgi-bin
		allow_methods POST
		upload_dir /Users/naomisterk/codam/webbieservie/www/uploads
	}
}